package models

import (
	"crypto/rand"
	"encoding/hex"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// InviteCode represents a referral invite code generated by a user.
type InviteCode struct {
	ID        uuid.UUID  `gorm:"type:uuid;primaryKey" json:"id"`
	UserID    uuid.UUID  `gorm:"type:uuid;not null;index" json:"user_id"`
	User      *User      `gorm:"foreignKey:UserID" json:"user,omitempty"`
	Code      string     `gorm:"type:varchar(16);uniqueIndex;not null" json:"code"`
	UsedBy    *uuid.UUID `gorm:"type:uuid" json:"used_by,omitempty"`
	UsedAt    *time.Time `json:"used_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
}

func (ic *InviteCode) BeforeCreate(tx *gorm.DB) error {
	if ic.ID == uuid.Nil {
		ic.ID = uuid.New()
	}
	if ic.Code == "" {
		ic.Code = GenerateInviteCode()
	}
	return nil
}

func GenerateInviteCode() string {
	b := make([]byte, 6)
	rand.Read(b)
	return hex.EncodeToString(b) // 12 chars
}

// SystemSetting stores key-value system settings.
type SystemSetting struct {
	Key       string    `gorm:"type:varchar(100);primaryKey" json:"key"`
	Value     string    `gorm:"type:text;not null;default:'false'" json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}
